SU-SWS/stanford_events

modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_events_importer.yml

- (Edit the above to reflect status)
- Changed the events importer ID settings for migrate

D8CORE-000: Events Updates

---

config/install/views.view.stanford_events.yml
config/install/views.view.stanford_events_past.yml
content/taxonomy_term/80a4d81e-8eff-4138-8529-5bff4f7952c1.json
content/taxonomy_term/f9979993-225b-4bdb-906f-daa2626332c5.json
modules/stanford_events_importer/config/install/core.entity_form_display.config_pages.stanford_events_importer.default.yml
modules/stanford_events_importer/config/install/field.field.config_pages.stanford_events_importer.su_event_xml_url.yml
modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_events_importer.yml
modules/stanford_events_importer/src/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidget.php
modules/stanford_events_importer/src/StanfordEventsImporter.php
modules/stanford_events_importer/stanford_events_importer.module
modules/stanford_events_importer/tests/src/Kernel/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
modules/stanford_events_importer/tests/src/Unit/Plugin/Field/FieldWidget/StanfordEventsImporterAPIURLFieldWidgetTest.php
modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php
tests/codeception/acceptance/StanfordEventsCest.php
tests/codeception/acceptance/StanfordEventsSeriesCest.php

- Adds coverage and fixes codeception tests
- Today please
- 10
- Review test code 
- Review circle run

Events, Series, and Importer Tests

---

config/install/core.entity_view_display.node.stanford_event.default.yml
config/install/views.view.stanford_events.yml

https://github.com/SU-SWS/stanford_profile/pull/233

Fix missing event title in views and re-ordered event node fields

---

composer.json
modules/stanford_events_importer/config/install/ultimate_cron.job.stanford_migrate_stanford_events_importer.yml
modules/stanford_events_importer/stanford_events_importer.info.yml
tests/codeception/acceptance/StanfordEventsCest.php
tests/codeception/acceptance/StanfordEventsImporterCest.php

- Patches smart_date to avoid adding and adjusted timezone to the end of the format.
- June 30th
- medium/high (this is a reported and noticed bug)
1. Do a fresh build of the stanford_profile on cardinalsites or lelandd8
2. Configure the importer to import 'featured' events and import them
3. View the `/events` page as anonymous and see the duplicated timezones
4. Apply the patch added in this PR to smart_date
5. Clear render cache and review the `/events` page again as anonymous and see the second time & zone go away.
- D8CORE
- SOE
- https://www.drupal.org/project/smart_date/issues/3154741
- @cynmij 
- @jenbreese 
- D8CORE-2223
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqM …

D8CORE-2223: Add smart_date patch to prevent duplicate timezones.

---

composer.json

- Removed unused dependency
- 
- 

Removed views_taxonomy_term_name_depth thats not used

---

composer.json

- The patch was merged and released in 3.8
- Today?
- Medium. Patch is breaking builds.
- Check code
- Wait for tests to pass
- Review issue: https://www.drupal.org/project/ds/issues/3154727

DEVOPS-000: https://www.drupal.org/project/ds/issues/3154727 Patch merged in

---

CHANGELOG.md
composer.json
modules/stanford_events_importer/stanford_events_importer.info.yml
modules/stanford_events_series/stanford_events_series.info.yml
stanford_events.info.yml

- Automated pull request created via HAL 9000.  See changes below for details.
- As soon as possible
The following changes since commit 0522a1fe2ef430850b5ab91b6942206ff5d83a8e:
Merge pull request #19 from SU-SWS/release-8.1.1 (2020-07-13 13:38:32 -0700)
are available in the Git repository at:
./ 
for you to fetch changes up to 021727e939aa512ec70c4d97a03044b7fda627d9:
8.1.2 (2020-08-07 11:53:28 -0600)
----------------------------------------------------------------
Ian Monroe (1):
8.1.2
Sherakama (1):
DEVOPS-000: https://www.drupal.org/project/ds/issues/3154727 Patch merged in (#21)
pookmish (1):
Removed views_taxonomy_term_name_depth thats not used (#20)
sws-developers@lists.stanford.edu (1):
Back to dev
CHANGELOG.md                                               |  7 +++++++ …

"8.x-1.x >  8.1.2

---

stanford_events.info.yml
tests/codeception/acceptance/StanfordEventsCest.php
tests/codeception/acceptance/StanfordEventsImporterCest.php
tests/codeception/acceptance/StanfordEventsSeriesCest.php

Fixing the tests: enabling modules we have to pass the `-y` so drush doesn't get stuck.

---

.circleci/config.yml
composer.json
config/install/core.entity_view_display.node.stanford_event.stanford_card.yml
config/install/core.entity_view_mode.node.stanford_card.yml
config/install/views.view.stanford_events.yml
dist/css/stanford_events.event-card.css
lib/scss/components/event-card/stanford_events.event-card.scss
stanford_events.info.yml
templates/components/events-card/events-card.html.twig
templates/components/events-card/events-card.ui_patterns.yml
templates/components/events-list/events-list.ui_patterns.yml
tests/codeception/acceptance/StanfordEventsCest.php
tests/codeception/acceptance/StanfordEventsImporterCest.php
tests/codeception/acceptance/StanfordEventsSeriesCest.php
webpack.config.js

- Added events card pattern and card view mode with respective configs
- Added events card view display.
- https://github.com/SU-SWS/stanford_profile/pull/313
- 10/38
- medium
1. follow the steps in https://github.com/SU-SWS/stanford_profile/pull/313

D8CORE-2737 Event card display mode and view list.

---

modules/stanford_events_importer/tests/src/Unit/StanfordEventsImporterTest.php

- Updated phpunit tests so they will pass on phpunit 8 with drupal 9
- whenever
- low

Update tests for D9 phpunit

---

config/install/core.entity_view_display.node.stanford_event.default.yml

- just a simple config change to add a separator for the date strings
- see related PR for the profile: https://github.com/SU-SWS/stanford_profile/pull/338
- Dec.3
- How critical is this PR on a 1-10 scale?  1 of 10
2. Navigate to...
3. Verify...
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML …

D8CORE-2325: Added separator for date field.

---

stanford_events.module

- In an event that has a schedule, if you create a scheduled item which spans multiple days, only the first day was displayed in the schedule. This PR corrects that.
- 12/3 
- 3 of 10
2. create an Event item
3. Create a schedule of stuff for the event.  Create at least one scheduled item which spans more than one day.
4. Observe that for single day scheduled items, you get a single day, and for multiple day scheduled items, you get a span of dates.
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)
- [AMP …

D8CORE-2326: Modified the event schedule date formatting to account for multiple days.

---

.circleci/config.yml
composer.json
tests/codeception/acceptance/StanfordEventsImporterCest.php
tests/codeception/acceptance/StanfordEventsSeriesCest.php

- Updated circleci to test D8 and D9
- updated composer dependencies.
- Fixed tests.
- 1/15/2021
- medium
1. review passing tests

Updated circleci testing

---

composer.json
stanford_events.info.yml

- Updated components API definition https://www.drupal.org/docs/contributed-modules/components/registering-twig-namespaces#s-old-api-in-8x-1x
- Moved all the patches to the shared `drupal-patches` package
- :shrug: 
- low
1. checkout this branch
2. clear caches
3. view the site and ensure you don't get any twig errors.

Move patches to shared package

---

config/install/views.view.stanford_events.yml

- This brings in the changes from: https://github.com/SU-SWS/stanford_profile/pull/397
- 4/7
- Not critical. We're just codifiying a change in the view.
- Test via https://github.com/SU-SWS/stanford_profile/pull/397

D8CORE-4033: updated view config with past events filters

---

templates/block/block--menu-block--stanford-event-types.html.twig

- Added the skip to secondary nav link
- June 26
- Med
- Accessibility
- Events
- News
- People
- medium
1. Check out this branch and the related pull request
3. Make sure you have news, people, past events, event series, and events
4. Verify you can use the skip to links for both the secondary navigation and the main content well.  
5. This change is big and must be reviewed by @cjwest 
- Is there a config:export in this PR that changes the config sync directory?
- [D8CORE-4378](https://stanfordits.atlassian.net/browse/D8CORE-4378)
- https://github.com/SU-SWS/stanford_news/pull/127
- https://github.com/SU-SWS/stanford_person/pull/145
- …

D8CORE-4378: fixing the skip to secondary nav link

---

templates/block/block--menu-block--stanford-event-types.html.twig

- Adding the Skip to Main on the topics menu for Events, News, and People. Publications is in a different pull request.
- 7/6
- Effects SBT
- and Subthemes
- Med
3. Navigate to /events
4. Verify you can tab to the skip to main link on the topics menu. 
5. Navigate to /events filtered page 
6. Verify you can tab to the skip to main link on the topics menu. 
- Is there a config:export in this PR that changes the config sync directory? NO
- Event Module
- Person Module
- News Module
- [D8CORE-4508](https://stanfordits.atlassian.net/browse/D8CORE-4508)
- https://github.com/SU-SWS/stanford_news/pull/128
- https://github.com/SU-SWS/stanford_person/pull/147
- @cjwest 
- [AMP …

D8CORE-4508: adding skip to main on the topic menu

---

templates/components/list/list.html.twig

- adding accessibility tags for screen readers
- Aug 2
- Med
- Events list and filtered page
- Events paragraph list
- Med
3. Navigate to /events and listen to see if it sounds correct, @cjwest.
4. Navigate to  a page with events in a list paragraph and listen to see if it sounds correct, @cjwest.
4. Verify
- Is there a config:export in this PR that changes the config sync directory? NO
- https://stanfordits.atlassian.net/browse/D8CORE-2520
- Anyone who should be notified? (`@mention` them here)
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j …

D8CORE-2520: date labeling for Events

---

composer.json
modules/stanford_events_importer/config/install/migrate_plus.migration.stanford_localist_importer.yml

- A simple one-liner to add the Localist URL to the external source field for imported localist events.
- Goes along with: https://github.com/SU-SWS/stanford_profile/pull/471
- code cutoff.
- 2
- normal
1. This is the same change as in https://github.com/SU-SWS/stanford_profile/pull/471 which is probably the right place to test it.  This PR just pulls the same change into this repo for consistency.
- Is there a config:export in this PR that changes the config sync directory? NO
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)
- [AMP …

Added localist URL to external source field.

---

modules/stanford_events_series/config/install/core.entity_view_display.node.stanford_event_series.default.yml

- The event series' components were full width instead of flex-10-of-12.
- 1/21/2022
- Normal
- Normal
3. If using the amptesting-test content you can use these links to check it out. 
4. http://core.loc/event/series/test-event-series-lorem-ipsum
5. http://core.loc/event/series/founding-fathers-event-series
6. http://core.loc/event/series/constitution-united-states
3. If not, then create an event series with a heading, subheading, dek and then component content.
4. Verify that the headings align and the components are in the flex-10-of-12 
Design: not pictured is the components which should also align. 
- Is there a config:export in this PR that changes the config sync directory? YES
- Does this PR impact …

D8CORE-5000: Constraining the components to the 10-of-12 col width

---

composer.json

- D8CORE-5102 Events mini-calendar using PDB (#101)
- Updated views_infinite_scroll module
- (Edit the above to reflect status)
- TL;DR - what's this PR for?
- When does this need to be reviewed by?
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?
- How urgent is this? (Normal, High)
3. Navigate to...
4. Verify...
- Is there a config:export in this PR that changes the config sync directory?
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that …

update views infinite scroll
